/**
 * arXiv category taxonomy — typed accessors over the cached JSON.
 *
 * The JSON is generated by `scripts/sync-taxonomy.mjs` (run
 * `pnpm sync:taxonomy`). Everything here is build-time / SSR only —
 * a small in-memory Map over a static file, no network.
 */
import taxonomy from '../data/arxiv-taxonomy.json';

export interface ArxivCategory {
  /** Category ID, e.g. "q-bio.BM". */
  readonly id: string;
  /** Human-readable name, e.g. "Biomolecules". */
  readonly name: string;
  /** Long-form description from the arXiv taxonomy page. */
  readonly description: string;
  /** Parent group display name, e.g. "Quantitative Biology". */
  readonly group: string;
  /** Parent group slug, e.g. "q-bio". */
  readonly groupId: string;
}

export const allCategories: ReadonlyArray<ArxivCategory> =
  taxonomy.categories as ArxivCategory[];

const byId = new Map<string, ArxivCategory>(
  allCategories.map((c) => [c.id, c]),
);

/** Look up a category by ID; undefined for unknown / legacy tags. */
export function getCategory(id: string): ArxivCategory | undefined {
  return byId.get(id);
}

/** True when `id` is a real arXiv category in the cached taxonomy. */
export function isValidCategory(id: string): boolean {
  return byId.has(id);
}

/** All known category IDs (handy for schema validation). */
export const categoryIds: ReadonlyArray<string> = allCategories.map((c) => c.id);
